### ISSUE TITLE
支持手机浏览器吗

### ISSUE THREAD

**Issue by MichealWen** [ChiChou/StreetView#5]
手机浏览器上也无法查看

**Comment by ChiChou** [comment]
这个版本是有兼容性问题，见 #3 

打算重写了，demo 版测试过 iOS 可以做，MIUI 也正常；但是Android 相当大部分机型不支持浏览器 3d :cry:

**Comment by MichealWen** [comment]
我的手机是MIUI 6，特意下了chrome和firefox测试，都不能正常显示，这个程序完全是你自己写的吗，还是有参考什么其它代码，如果有，我也想去参考一下。
PS：期待你的新版本

**Comment by ChiChou** [comment]
@MichealWen 支持移动设备的没 po 上来，是完全重写了，换了一下贴图的格式，UI 交互什么的还没做

**Comment by MichealWen** [comment]
看到了一个你的3D 数字地球，是你自己的项目吗，我们公司最近在做一个类似的项目，基于CesiumJS

**Comment by ChiChou** [comment]
CesiumJS 我看过，他们是偏向于 Google Earth 级别的精度（贴图用的是真实的地图 tile），拖动体验有一些奇怪；我们做的只是一些普通的可视化，追求视觉自定义和一些特殊的覆盖物的效果，所以就自己造轮子。

**Comment by MichealWen** [comment]
也是公司项目吗，

**Comment by ChiChou** [comment]
算是吧，还是试验阶段

**Comment by ChiChou** [comment]
支持 MIUI 等手机浏览器的 DEMO 
http://chichou.0ginr.com/app/pixel/

照片是自己用手机拍摄拼接的

**Comment by ChiChou** [comment]
dev 分支中已解决，推荐使用 iOS
